Remove bad code for fallback upstream_jsonrpc
This was added by accident and it causing the build to fail

```
   = note: `#[warn(unused_imports)]` on by default
error[E0609]: no field `upstream` on type `Arc<api_jsonrpc::State>`
   --> src/rpc/api_jsonrpc.rs:846:48
    |
846 |             if let Some(upstream) = self.state.upstream.as_ref() {
    |                                                ^^^^^^^^ unknown field
    |
    = note: available fields are: `epoch_schedule`, `stored_slots`, `request_timeout`, `gsfa_limit`, `gss_transaction_history` ... and 5 others
error[E0609]: no field `upstream` on type `Arc<api_jsonrpc::State>`
    --> src/rpc/api_jsonrpc.rs:1484:48
     |
1484 |             if let Some(upstream) = self.state.upstream.as_ref() {
     |                                                ^^^^^^^^ unknown field
     |
     = note: available fields are: `epoch_schedule`, `stored_slots`, `request_timeout`, `gsfa_limit`, `gss_transaction_history` ... and 5 others
error[E0282]: type annotations needed
    --> src/rpc/api_jsonrpc.rs:1488:31
```

Signed-off-by: Daniel Camargo <67828229+dancamarg0@users.noreply.github.com>